### ISSUE TITLE
How to create a new forum topic?

### ISSUE THREAD

**Issue by zoltanhalasz** [ElliottBrand/BlazorForum#28]
I started to run the application, after logging in as a user.
But where can open a new topic? There is no menu item for that.

![no topic](https://user-images.githubusercontent.com/42749923/109395786-f032fb80-7936-11eb-8157-b312757b483d.png)

**Comment by ElliottBrand** [comment]
To create a forum topic, you'll need to create a forum in the admin area first (/admin/manage/forums/). Then you should be able to navigate to the forum in the frontend of the site and create a new topic there.

**Comment by ElliottBrand** [comment]
Hi, the forum must be created in the administration area, then a topic can be created in the frontend.
