### ISSUE TITLE
How to create a new topic and new category

### ISSUE THREAD

**Issue by ltemimi** [ElliottBrand/BlazorForum#30]
Hi

I have created a new forum and unable to see how to create a new topic and category . no menu for it

Please help

![image](https://user-images.githubusercontent.com/5493492/117992759-13b2f300-b337-11eb-9941-187235de0ae1.png)

**Comment by ltemimi** [comment]
Hi

I cannot see any way I can create a category in the admin area no menu for it

Thanks

Laz

**Comment by ElliottBrand** [comment]
First clicks on "Forums" in the admin menu, then click on the Forum that you want to add the category to. In that next page you should see the area to add a category.
