### ISSUE TITLE
Invalid login

### ISSUE THREAD

**Issue by ltemimi** [ElliottBrand/BlazorForum#31]
Hi

I have registered created forum etc.. then to test security I logged out and tried to log back in to navail. my user name and password are correct.

Could you please confirm this app is ready to use. I intend to use it online.

Regards

Laz
![image](https://user-images.githubusercontent.com/5493492/117996270-eb78c380-b339-11eb-9d97-35a11b4e0322.png)

**Comment by ElliottBrand** [comment]
The login should be working fine (and does work fine at blazorforums.net, which is the same app), however, the app never had an official release created and is not really considered production ready. This is mentioned in the opening paragraph at https://github.com/ElliottBrand/BlazorForum/. This app was started when Blazor first came out, hasn't had much work done to it in a while, and no developers ever joined in to contribute. So, I wouldn't recommend using it in production unless you plan on taking the code and using it as a starting point and building it out yourself from here.

**Comment by ltemimi** [comment]
Hi

Thanks for your response. I am grateful for the app

regards
Laz
